// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raft

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RaftCommand struct {
	_tab flatbuffers.Table
}

func GetRootAsRaftCommand(buf []byte, offset flatbuffers.UOffsetT) *RaftCommand {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RaftCommand{}
	x.Init(buf, n+offset)
	return x
}

func FinishRaftCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRaftCommand(buf []byte, offset flatbuffers.UOffsetT) *RaftCommand {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RaftCommand{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRaftCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RaftCommand) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RaftCommand) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RaftCommand) Type() CommandType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return CommandType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *RaftCommand) MutateType(n CommandType) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *RaftCommand) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *RaftCommand) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *RaftCommand) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RaftCommand) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *RaftCommand) PayloadType() CommandPayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return CommandPayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *RaftCommand) MutatePayloadType(n CommandPayload) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *RaftCommand) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func RaftCommandStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func RaftCommandAddType(builder *flatbuffers.Builder, type_ CommandType) {
	builder.PrependInt8Slot(0, int8(type_), 0)
}
func RaftCommandAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func RaftCommandStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func RaftCommandAddPayloadType(builder *flatbuffers.Builder, payloadType CommandPayload) {
	builder.PrependByteSlot(2, byte(payloadType), 0)
}
func RaftCommandAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(payload), 0)
}
func RaftCommandEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
