// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raft

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SegmentStateEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsSegmentStateEntry(buf []byte, offset flatbuffers.UOffsetT) *SegmentStateEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SegmentStateEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishSegmentStateEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSegmentStateEntry(buf []byte, offset flatbuffers.UOffsetT) *SegmentStateEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SegmentStateEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSegmentStateEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SegmentStateEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SegmentStateEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SegmentStateEntry) SegmentId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentStateEntry) MutateSegmentId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *SegmentStateEntry) State() SegmentState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return SegmentState(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *SegmentStateEntry) MutateState(n SegmentState) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func SegmentStateEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SegmentStateEntryAddSegmentId(builder *flatbuffers.Builder, segmentId uint32) {
	builder.PrependUint32Slot(0, segmentId, 0)
}
func SegmentStateEntryAddState(builder *flatbuffers.Builder, state SegmentState) {
	builder.PrependInt8Slot(1, int8(state), 0)
}
func SegmentStateEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
