// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raft

import "strconv"

type SegmentState int8

const (
	SegmentStateACTIVE            SegmentState = 0
	SegmentStatePENDING_UPLOAD    SegmentState = 1
	SegmentStateUPLOADED          SegmentState = 2
	SegmentStatePARQUET_COMMITTED SegmentState = 3
)

var EnumNamesSegmentState = map[SegmentState]string{
	SegmentStateACTIVE:            "ACTIVE",
	SegmentStatePENDING_UPLOAD:    "PENDING_UPLOAD",
	SegmentStateUPLOADED:          "UPLOADED",
	SegmentStatePARQUET_COMMITTED: "PARQUET_COMMITTED",
}

var EnumValuesSegmentState = map[string]SegmentState{
	"ACTIVE":            SegmentStateACTIVE,
	"PENDING_UPLOAD":    SegmentStatePENDING_UPLOAD,
	"UPLOADED":          SegmentStateUPLOADED,
	"PARQUET_COMMITTED": SegmentStatePARQUET_COMMITTED,
}

func (v SegmentState) String() string {
	if s, ok := EnumNamesSegmentState[v]; ok {
		return s
	}
	return "SegmentState(" + strconv.FormatInt(int64(v), 10) + ")"
}
