// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raft

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SegmentUploadedCommand struct {
	_tab flatbuffers.Table
}

func GetRootAsSegmentUploadedCommand(buf []byte, offset flatbuffers.UOffsetT) *SegmentUploadedCommand {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SegmentUploadedCommand{}
	x.Init(buf, n+offset)
	return x
}

func FinishSegmentUploadedCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSegmentUploadedCommand(buf []byte, offset flatbuffers.UOffsetT) *SegmentUploadedCommand {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SegmentUploadedCommand{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSegmentUploadedCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SegmentUploadedCommand) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SegmentUploadedCommand) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SegmentUploadedCommand) ShardId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SegmentUploadedCommand) SegmentId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentUploadedCommand) MutateSegmentId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *SegmentUploadedCommand) ObjectBucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SegmentUploadedCommand) ObjectKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SegmentUploadedCommand) ObjectSizeBytes() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentUploadedCommand) MutateObjectSizeBytes(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *SegmentUploadedCommand) ObjectChecksum() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SegmentUploadedCommandStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func SegmentUploadedCommandAddShardId(builder *flatbuffers.Builder, shardId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(shardId), 0)
}
func SegmentUploadedCommandAddSegmentId(builder *flatbuffers.Builder, segmentId uint32) {
	builder.PrependUint32Slot(1, segmentId, 0)
}
func SegmentUploadedCommandAddObjectBucket(builder *flatbuffers.Builder, objectBucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(objectBucket), 0)
}
func SegmentUploadedCommandAddObjectKey(builder *flatbuffers.Builder, objectKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(objectKey), 0)
}
func SegmentUploadedCommandAddObjectSizeBytes(builder *flatbuffers.Builder, objectSizeBytes uint64) {
	builder.PrependUint64Slot(4, objectSizeBytes, 0)
}
func SegmentUploadedCommandAddObjectChecksum(builder *flatbuffers.Builder, objectChecksum flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(objectChecksum), 0)
}
func SegmentUploadedCommandEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
