// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raft

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SegmentParquetCommittedCommand struct {
	_tab flatbuffers.Table
}

func GetRootAsSegmentParquetCommittedCommand(buf []byte, offset flatbuffers.UOffsetT) *SegmentParquetCommittedCommand {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SegmentParquetCommittedCommand{}
	x.Init(buf, n+offset)
	return x
}

func FinishSegmentParquetCommittedCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSegmentParquetCommittedCommand(buf []byte, offset flatbuffers.UOffsetT) *SegmentParquetCommittedCommand {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SegmentParquetCommittedCommand{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSegmentParquetCommittedCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SegmentParquetCommittedCommand) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SegmentParquetCommittedCommand) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SegmentParquetCommittedCommand) ShardId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SegmentParquetCommittedCommand) SegmentId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentParquetCommittedCommand) MutateSegmentId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *SegmentParquetCommittedCommand) ParquetFiles(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *SegmentParquetCommittedCommand) ParquetFilesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SegmentParquetCommittedCommand) IcebergTable() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SegmentParquetCommittedCommand) IcebergSnapshotId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentParquetCommittedCommand) MutateIcebergSnapshotId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func SegmentParquetCommittedCommandStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func SegmentParquetCommittedCommandAddShardId(builder *flatbuffers.Builder, shardId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(shardId), 0)
}
func SegmentParquetCommittedCommandAddSegmentId(builder *flatbuffers.Builder, segmentId uint32) {
	builder.PrependUint32Slot(1, segmentId, 0)
}
func SegmentParquetCommittedCommandAddParquetFiles(builder *flatbuffers.Builder, parquetFiles flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(parquetFiles), 0)
}
func SegmentParquetCommittedCommandStartParquetFilesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SegmentParquetCommittedCommandAddIcebergTable(builder *flatbuffers.Builder, icebergTable flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(icebergTable), 0)
}
func SegmentParquetCommittedCommandAddIcebergSnapshotId(builder *flatbuffers.Builder, icebergSnapshotId uint64) {
	builder.PrependUint64Slot(4, icebergSnapshotId, 0)
}
func SegmentParquetCommittedCommandEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
