// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raft

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SegmentStateSnapshot struct {
	_tab flatbuffers.Table
}

func GetRootAsSegmentStateSnapshot(buf []byte, offset flatbuffers.UOffsetT) *SegmentStateSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SegmentStateSnapshot{}
	x.Init(buf, n+offset)
	return x
}

func FinishSegmentStateSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSegmentStateSnapshot(buf []byte, offset flatbuffers.UOffsetT) *SegmentStateSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SegmentStateSnapshot{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSegmentStateSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SegmentStateSnapshot) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SegmentStateSnapshot) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SegmentStateSnapshot) ShardId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SegmentStateSnapshot) Segments(obj *SegmentStateEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SegmentStateSnapshot) SegmentsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SegmentStateSnapshot) LastAppliedIndex() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentStateSnapshot) MutateLastAppliedIndex(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *SegmentStateSnapshot) LastAppliedTerm() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentStateSnapshot) MutateLastAppliedTerm(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func SegmentStateSnapshotStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func SegmentStateSnapshotAddShardId(builder *flatbuffers.Builder, shardId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(shardId), 0)
}
func SegmentStateSnapshotAddSegments(builder *flatbuffers.Builder, segments flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(segments), 0)
}
func SegmentStateSnapshotStartSegmentsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SegmentStateSnapshotAddLastAppliedIndex(builder *flatbuffers.Builder, lastAppliedIndex uint64) {
	builder.PrependUint64Slot(2, lastAppliedIndex, 0)
}
func SegmentStateSnapshotAddLastAppliedTerm(builder *flatbuffers.Builder, lastAppliedTerm uint64) {
	builder.PrependUint64Slot(3, lastAppliedTerm, 0)
}
func SegmentStateSnapshotEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
